In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

In [ ]:
movies = pd.read_csv('/content/drive/MyDrive/data/tmdb_5000_movies.csv')
movies

budget  ... vote_count
0     237000000  ...      11800
1     300000000  ...       4500
2     245000000  ...       4466
3     250000000  ...       9106
4     260000000  ...       2124
...         ...  ...        ...
4798     220000  ...        238
4799       9000  ...          5
4800          0  ...          6
4801          0  ...          7
4802          0  ...         16

[4803 rows x 20 columns]

In [ ]:
movies_df = movies[['id', 'title', 'genres', 'vote_average', 'vote_count', 'popularity', 'keywords', 'overview']]
movies_df

id  ...                                           overview
0      19995  ...  In the 22nd century, a paraplegic Marine is di...
1        285  ...  Captain Barbossa, long believed to be dead, ha...
2     206647  ...  A cryptic message from Bond’s past sends him o...
3      49026  ...  Following the death of District Attorney Harve...
4      49529  ...  John Carter is a war-weary, former military ca...
...      ...  ...                                                ...
4798    9367  ...  El Mariachi just wants to play his guitar and ...
4799   72766  ...  A newlywed couple's honeymoon is upended by th...
4800  231617  ...  "Signed, Sealed, Delivered" introduces a dedic...
4801  126186  ...  When ambitious New York attorney Sam is sent t...
4802   25975  ...  Ever since the second grade when he first saw ...

[4803 rows x 8 columns]

In [ ]:
pd.set_option('max_colwidth', 200)
movies_df[['genres', 'keywords']][:1]

genres                                                                                                                                                                                                 keywords
0  [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]  [{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name...

In [ ]:
type(movies_df[['genres', 'keywords']][:1])

pandas.core.frame.DataFrame

In [ ]:
from ast import literal_eval

# literal_eval('{"a":12}')

movies_df['genres'] = movies_df['genres'].apply(literal_eval) # 파이썬 코드로 바꿔줌
movies_df['keywords'] = movies_df['keywords'].apply(literal_eval)

movies_df['genres']

0       [{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 878, 'name': 'Science Fiction'}]
1                                               [{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 28, 'name': 'Action'}]
2                                                 [{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 80, 'name': 'Crime'}]
3                     [{'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}, {'id': 53, 'name': 'Thriller'}]
4                                      [{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 878, 'name': 'Science Fiction'}]
                                                                         ...                                                                  
4798                                               [{'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}, {'id': 53, 'name': 'Thriller'}]

In [ ]:
movies_df['genres'] = movies_df['genres'].apply(lambda x : [y['name'] for y in x])
movies_df['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...                      
4798                        [Action, Crime, Thriller]
4799                                [Comedy, Romance]
4800               [Comedy, Drama, Romance, TV Movie]
4801                                               []
4802                                    [Documentary]
Name: genres, Length: 4803, dtype: object

In [ ]:
movies_df['keywords'] = movies_df['keywords'].apply(lambda x : [y['name'] for y in x])
movies_df['keywords']

0       [culture clash, future, space war, space colony, society, space travel, futuristic, romance, space, alien, tribe, alien planet, cgi, marine, soldier, battle, love affair, anti war, power relations...
1       [ocean, drug abuse, exotic island, east india trading company, love of one's life, traitor, shipwreck, strong woman, ship, alliance, calypso, afterlife, fighter, pirate, swashbuckler, aftercredits...
2                                                                                                                      [spy, based on novel, secret agent, sequel, mi6, british secret service, united kingdom]
3       [dc comics, crime fighter, terrorist, secret identity, burglar, hostage drama, time bomb, gotham city, vigilante, cover-up, superhero, villainess, tragic hero, terrorism, destruction, catwoman, ca...
4       [based on novel, mars, medallion, space travel, princess, alien, steampunk, martian, escape, edgar rice burroughs, alien race, superhuman strength, mars civiliz

In [ ]:
movies_df[['genres', 'keywords']]

genres                                                                                                                                                                                                 keywords
0     [Action, Adventure, Fantasy, Science Fiction]  [culture clash, future, space war, space colony, society, space travel, futuristic, romance, space, alien, tribe, alien planet, cgi, marine, soldier, battle, love affair, anti war, power relations...
1                      [Adventure, Fantasy, Action]  [ocean, drug abuse, exotic island, east india trading company, love of one's life, traitor, shipwreck, strong woman, ship, alliance, calypso, afterlife, fighter, pirate, swashbuckler, aftercredits...
2                        [Action, Adventure, Crime]                                                                                                                 [spy, based on novel, secret agent, sequel, mi6, british secret service, united kingdom]
3                  [Action, Crime, Drama, Thriller]  [dc comics, crime fighter, terrorist, secret identity, burglar, hostage drama, time bomb, gotham city, vigilante, cover-up, superhero, villainess, tragic hero, terrorism, destruction, catwoman, ca...
4              [Action, Adventure, Science Fiction]  [based on novel, mars, medallion, space travel, princess, alien, steampunk, martian, escape, edgar rice burroughs, alien race, superhuman strength, mars civilization, sword and planet, 19th centur...
...                                             ...                                                                                                                                                                                                      ...
4798                      [Action, Crime, Thriller]                                                                                                                                     [united states–mexico barrier, legs, arms, paper knife, guitar case]
4799                              [Comedy, Romance]                                                                                                                                                                                                       []
4800             [Comedy, Drama, Romance, TV Movie]                                                                                                                               [date, love at first sight, narration, investigation, team, postal worker]
4801                                             []                                                                                                                                                                                                       []
4802                                  [Documentary]                                                                                                                                                                [obsession, camcorder, crush, dream girl]

[4803 rows x 2 columns]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer # 자동으로 텍스트를 횟수만큼 벡터로 바꿔줌, 가중치도 줄 수 있음

In [ ]:
movies_df['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...                      
4798                        [Action, Crime, Thriller]
4799                                [Comedy, Romance]
4800               [Comedy, Drama, Romance, TV Movie]
4801                                               []
4802                                    [Documentary]
Name: genres, Length: 4803, dtype: object

In [ ]:
movies_df['genres_literal'] = movies_df['genres'].apply(lambda x : (' ').join(x))
count_vect = CountVectorizer()
genre_mat = count_vect.fit_transform(movies_df['genres_literal'])
genre_mat.shape

(4803, 22)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
genre_sim = cosine_similarity(genre_mat, genre_mat)
genre_sim[:1]

array([[1.        , 0.77459667, 0.51639778, ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
data = genre_sim.argsort() # 오름차순으로 정렬한거 인덱스 번호로 나타내기

In [ ]:
genre_sim[:1][0][46]

0.9999999999999999

In [ ]:
genre_sim_sorted_ind = data[:,::-1]
genre_sim_sorted_ind[:2]

array([[   0, 3494,   46, ..., 3038, 3037, 2401],
       [  19,  315,   38, ..., 3069, 3067, 2401]])

In [ ]:
title_movie = movies_df[movies_df['title'] == 'Spectre']
title_movie.index.values

array([2])

In [ ]:
def find_sim_movie(df, sorted_in, title_name, top_10=10):
    title_movie = df[df['title']==title_name]
    title_index = title_movie.index.values
    similiar_indexes = sorted_in[title_index, :top_10]
    similiar_indexes = similiar_indexes.reshape(-1)

    return df.iloc[similiar_indexes]

In [ ]:
similiar_movies = find_sim_movie(movies_df, genre_sim_sorted_ind, 'The Godfather', 10)
similiar_movies[['title', 'vote_average']]

title  vote_average
3337               The Godfather           8.4
883          Catch Me If You Can           7.7
2801                 The Funeral           7.3
4065                  Mi America           0.0
3112     Blood Done Sign My Name           6.0
2072             Freedom Writers           7.5
1370                          21           6.5
1149             American Hustle           6.8
2582  The Place Beyond the Pines           6.8
3012               The Outsiders           6.9

In [ ]:
movies_df[['title', 'vote_average', 'vote_count']].sort_values('vote_average', ascending = False)[:10]

title  vote_average  vote_count
3519          Stiff Upper Lips          10.0           1
4247     Me You and Five Bucks          10.0           2
4045     Dancer, Texas Pop. 81          10.0           1
4662            Little Big Top          10.0           1
3992                 Sardaarji           9.5           2
2386            One Man's Hero           9.3           2
2970        There Goes My Baby           8.5           2
1881  The Shawshank Redemption           8.5        8205
2796     The Prisoner of Zenda           8.4          11
3337             The Godfather           8.4        5893

In [ ]:
C = movies_df['vote_average'].mean()
m = movies_df['vote_count'].quantile(0.6)
C = round(C, 3)
m = round(m, 3)
print(C, m)

6.092 370.2


In [ ]:
percentile = 0.6
C = movies_df['vote_average'].mean()
m = movies_df['vote_count'].quantile(percentile)

def weight_vote_average(record):
    v = record['vote_count']
    R = record['vote_average']
    return ((v/(v+m)) * R + ((m/(m+v)))*C)

In [ ]:
movies_df['weight_vote'] = movies_df.apply(weight_vote_average, axis=1)
movies_df.head()

id  ... weight_vote
0   19995  ...    7.166301
1     285  ...    6.838594
2  206647  ...    6.284091
3   49026  ...    7.541095
4   49529  ...    6.098838

[5 rows x 10 columns]

In [ ]:
movies_df[['title', 'weight_vote', 'vote_count']].sort_values('weight_vote', ascending=False)[:10]

title  weight_vote  vote_count
1881  The Shawshank Redemption     8.396052        8205
3337             The Godfather     8.263591        5893
662                 Fight Club     8.216455        9413
3232              Pulp Fiction     8.207102        8428
65             The Dark Knight     8.136930       12002
1818          Schindler's List     8.126069        4329
3865                  Whiplash     8.123248        4254
809               Forrest Gump     8.105954        7927
2294             Spirited Away     8.105867        3840
2731    The Godfather: Part II     8.079586        3338